Ctrl-Shift-Z 	: 	409
Ctrl-Shift-Z 	: 	UKR [409] [] 	 
Ctrl-Shift-Z 	: 	UKR [409] 409 #Line with tabs
#This is a conf file for language shortcut
# Example use
#Language codes: https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-language-pack-default-values?view=windows-11




Ctrl-K Eng [409] 409
Ctrl-Shift-Z : Eng [409] 409
Ctrl-Shift-Z 	: 	UKR [409] 409 #Line with tabs
